//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIReHex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DetailsRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DetailsRu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIReHex.DetailsRu", typeof(DetailsRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключатель скорости игры имеет значения по умолчанию:
        ///скорость x1 в нижнем положении, и x2 в верхнем положении..
        /// </summary>
        public static string GameSpeedDefaultRB {
            get {
                return ResourceManager.GetString("GameSpeedDefaultRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повышенные значения в переключателе скорости игры:
        ///скорость x2 в нижнем положении, и x3 в верхнем положении..
        /// </summary>
        public static string GameSpeedFastRB {
            get {
                return ResourceManager.GetString("GameSpeedFastRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значительно ускоряет игру, если переключатель скорости нажат мышкой в верхнее положение. Используйте клавиатуру для переключения скорости на нормальные значения..
        /// </summary>
        public static string GameSpeedSuperCB {
            get {
                return ResourceManager.GetString("GameSpeedSuperCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта настройка отключает деление опыта на всех учасников группы, таким образом каждый получает полное значение опыта.
        ///Внимание: Персонажи всеравно могут получать различное кол-во опыта, это зависит от их интеллекта..
        /// </summary>
        public static string PartyExpCB {
            get {
                return ResourceManager.GetString("PartyExpCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бег не расходует запас сил, если вы не в бою. Это экономит наше время, когда надо преодолеть большие расстояния..
        /// </summary>
        public static string RunAmountBattleCB {
            get {
                return ResourceManager.GetString("RunAmountBattleCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время бега по умолчанию..
        /// </summary>
        public static string RunAmountDefaultRB {
            get {
                return ResourceManager.GetString("RunAmountDefaultRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персонажи бегают в 2 раза дольше..
        /// </summary>
        public static string RunAmountDoubleRB {
            get {
                return ResourceManager.GetString("RunAmountDoubleRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время бега зависит от запаса сил персонажа. В начале игры может показаться, что Зак бегает совсем не долго, но позднее, с ростом опыта и запаса сил, все бегают гораздо дольше..
        /// </summary>
        public static string RunAmountManaRB {
            get {
                return ResourceManager.GetString("RunAmountManaRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исправлена ошибка разработчиков в формуле расчёта стоимости будущих уровней вторичных навыков. Эта информация отображается на правой панели, когда мышка наведена на навык..
        /// </summary>
        public static string SecondarySkillsCB {
            get {
                return ResourceManager.GetString("SecondarySkillsCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта настройка позволяет создавать сложные заклинания, даже если персонаж не сможет их использовать. Это очень полезно когда необходимо создать заклинание для магических жезлов или вещей..
        /// </summary>
        public static string SpellConstuctorCB {
            get {
                return ResourceManager.GetString("SpellConstuctorCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость игры в посёлках по умолчанию (x1)..
        /// </summary>
        public static string VillageSpeedDefaultRB {
            get {
                return ResourceManager.GetString("VillageSpeedDefaultRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость игры в посёлках x2..
        /// </summary>
        public static string VillageSpeedX2RB {
            get {
                return ResourceManager.GetString("VillageSpeedX2RB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость игры в посёлках x3..
        /// </summary>
        public static string VillageSpeedX3RB {
            get {
                return ResourceManager.GetString("VillageSpeedX3RB", resourceCulture);
            }
        }
    }
}
