//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIReHex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsRu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsRu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIReHex.StringsRu", typeof(StringsRu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл addon.dll уже был исправлен ранее..
        /// </summary>
        public static string AddonDllAlreadyFixed {
            get {
                return ResourceManager.GetString("AddonDllAlreadyFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось исправить выбранный файл addon.dll..
        /// </summary>
        public static string AddonDllError {
            get {
                return ResourceManager.GetString("AddonDllError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исправить addon.dll ?.
        /// </summary>
        public static string AddonDllMsgCaption {
            get {
                return ResourceManager.GetString("AddonDllMsgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите &quot;Да&quot; если при запуске игры у вас ошибка:
        ///&quot;Apply cannot be called from old loader.&quot;.
        /// </summary>
        public static string AddonDllMsgText {
            get {
                return ResourceManager.GetString("AddonDllMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновление файла....
        /// </summary>
        public static string ApplyingText {
            get {
                return ResourceManager.GetString("ApplyingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать бекап.
        /// </summary>
        public static string BackupCB {
            get {
                return ResourceManager.GetString("BackupCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово.
        /// </summary>
        public static string DoneText {
            get {
                return ResourceManager.GetString("DoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не найден.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартная скорость.
        /// </summary>
        public static string GameSpeedDefaultRB {
            get {
                return ResourceManager.GetString("GameSpeedDefaultRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высокая скорость.
        /// </summary>
        public static string GameSpeedFastRB {
            get {
                return ResourceManager.GetString("GameSpeedFastRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключатель скорости игры.
        /// </summary>
        public static string GameSpeedGroupBox {
            get {
                return ResourceManager.GetString("GameSpeedGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Супер скорость при выборе мышкой.
        /// </summary>
        public static string GameSpeedSuperCB {
            get {
                return ResourceManager.GetString("GameSpeedSuperCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный файл не совместим с текущей версией программы..
        /// </summary>
        public static string IncompatibleFile {
            get {
                return ResourceManager.GetString("IncompatibleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Определение настроек....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разное.
        /// </summary>
        public static string MiscellaneousGroupBox {
            get {
                return ResourceManager.GetString("MiscellaneousGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный файл частично не совместим с текущей версией программы. Убедитесь что установлена галочка &quot;Создать бекап&quot; перед применением изменений..
        /// </summary>
        public static string PartiallyCompatibleFile {
            get {
                return ResourceManager.GetString("PartiallyCompatibleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полный опыт для всех в группе.
        /// </summary>
        public static string PartyExpCB {
            get {
                return ResourceManager.GetString("PartyExpCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тратится до конца только в бою.
        /// </summary>
        public static string RunAmountBattleCB {
            get {
                return ResourceManager.GetString("RunAmountBattleCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартное время.
        /// </summary>
        public static string RunAmountDefaultRB {
            get {
                return ResourceManager.GetString("RunAmountDefaultRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удвоенное время.
        /// </summary>
        public static string RunAmountDoubleRB {
            get {
                return ResourceManager.GetString("RunAmountDoubleRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время бега.
        /// </summary>
        public static string RunAmountGroupBox {
            get {
                return ResourceManager.GetString("RunAmountGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зависит от запаса сил.
        /// </summary>
        public static string RunAmountManaRB {
            get {
                return ResourceManager.GetString("RunAmountManaRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фикс стоимости вторич. навыков.
        /// </summary>
        public static string SecondarySkillsCB {
            get {
                return ResourceManager.GetString("SecondarySkillsCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранный файл:.
        /// </summary>
        public static string SelectedFileLabel {
            get {
                return ResourceManager.GetString("SelectedFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать game.exe.
        /// </summary>
        public static string SelectExeButton {
            get {
                return ResourceManager.GetString("SelectExeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разблок. конструктор заклинаний.
        /// </summary>
        public static string SpellConstuctorCB {
            get {
                return ResourceManager.GetString("SpellConstuctorCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартная скорость.
        /// </summary>
        public static string VillageSpeedDefaultRB {
            get {
                return ResourceManager.GetString("VillageSpeedDefaultRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость игры в мирных зонах.
        /// </summary>
        public static string VillageSpeedGroupBox {
            get {
                return ResourceManager.GetString("VillageSpeedGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высокая скорость.
        /// </summary>
        public static string VillageSpeedX2RB {
            get {
                return ResourceManager.GetString("VillageSpeedX2RB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очень высокая скорость.
        /// </summary>
        public static string VillageSpeedX3RB {
            get {
                return ResourceManager.GetString("VillageSpeedX3RB", resourceCulture);
            }
        }
    }
}
