//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIReHex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EIReHex.StringsEn", typeof(StringsEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File addon.dll is already fixed..
        /// </summary>
        public static string AddonDllAlreadyFixed {
            get {
                return ResourceManager.GetString("AddonDllAlreadyFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fix this addon.dll..
        /// </summary>
        public static string AddonDllError {
            get {
                return ResourceManager.GetString("AddonDllError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix addon.dll ?.
        /// </summary>
        public static string AddonDllMsgCaption {
            get {
                return ResourceManager.GetString("AddonDllMsgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Yes&quot; if you are getting error like:
        ///&quot;Apply cannot be called from old loader.&quot;.
        /// </summary>
        public static string AddonDllMsgText {
            get {
                return ResourceManager.GetString("AddonDllMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes.
        /// </summary>
        public static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying file....
        /// </summary>
        public static string ApplyingText {
            get {
                return ResourceManager.GetString("ApplyingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make backup.
        /// </summary>
        public static string BackupCB {
            get {
                return ResourceManager.GetString("BackupCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneText {
            get {
                return ResourceManager.GetString("DoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default speed values.
        /// </summary>
        public static string GameSpeedDefaultRB {
            get {
                return ResourceManager.GetString("GameSpeedDefaultRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High speed values.
        /// </summary>
        public static string GameSpeedFastRB {
            get {
                return ResourceManager.GetString("GameSpeedFastRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game speed selector.
        /// </summary>
        public static string GameSpeedGroupBox {
            get {
                return ResourceManager.GetString("GameSpeedGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super speed when clicked using mouse.
        /// </summary>
        public static string GameSpeedSuperCB {
            get {
                return ResourceManager.GetString("GameSpeedSuperCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file is incompatible with current program version..
        /// </summary>
        public static string IncompatibleFile {
            get {
                return ResourceManager.GetString("IncompatibleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing file....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string MiscellaneousGroupBox {
            get {
                return ResourceManager.GetString("MiscellaneousGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file is partially incompatible with current program version. Please make sure the backup checkbox is checked and then apply changes..
        /// </summary>
        public static string PartiallyCompatibleFile {
            get {
                return ResourceManager.GetString("PartiallyCompatibleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full exp value for party members.
        /// </summary>
        public static string PartyExpCB {
            get {
                return ResourceManager.GetString("PartyExpCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited out of combat.
        /// </summary>
        public static string RunAmountBattleCB {
            get {
                return ResourceManager.GetString("RunAmountBattleCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        public static string RunAmountDefaultRB {
            get {
                return ResourceManager.GetString("RunAmountDefaultRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twice longer.
        /// </summary>
        public static string RunAmountDoubleRB {
            get {
                return ResourceManager.GetString("RunAmountDoubleRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters running time.
        /// </summary>
        public static string RunAmountGroupBox {
            get {
                return ResourceManager.GetString("RunAmountGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depends on stamina.
        /// </summary>
        public static string RunAmountManaRB {
            get {
                return ResourceManager.GetString("RunAmountManaRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix secondary skills cost.
        /// </summary>
        public static string SecondarySkillsCB {
            get {
                return ResourceManager.GetString("SecondarySkillsCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file:.
        /// </summary>
        public static string SelectedFileLabel {
            get {
                return ResourceManager.GetString("SelectedFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select game.exe.
        /// </summary>
        public static string SelectExeButton {
            get {
                return ResourceManager.GetString("SelectExeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked spell constructor.
        /// </summary>
        public static string SpellConstuctorCB {
            get {
                return ResourceManager.GetString("SpellConstuctorCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default speed.
        /// </summary>
        public static string VillageSpeedDefaultRB {
            get {
                return ResourceManager.GetString("VillageSpeedDefaultRB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game speed in briefing zones.
        /// </summary>
        public static string VillageSpeedGroupBox {
            get {
                return ResourceManager.GetString("VillageSpeedGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High speed.
        /// </summary>
        public static string VillageSpeedX2RB {
            get {
                return ResourceManager.GetString("VillageSpeedX2RB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very high speed.
        /// </summary>
        public static string VillageSpeedX3RB {
            get {
                return ResourceManager.GetString("VillageSpeedX3RB", resourceCulture);
            }
        }
    }
}
